CREATE OR REPLACE FUNCTION InsertOnFeed()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO Feed (IDCanal, IDVideo)
    SELECT IDFonte, NEW.ID
    FROM Inscricoes
    WHERE IDFonte = (SELECT IDCanal FROM Post WHERE ID = NEW.IDPost);

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
    
CREATE TRIGGER UpdateFeed
AFTER INSERT ON Video
FOR EACH ROW
EXECUTE FUNCTION InsertOnFeed();


